version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: CleanupScript.sh
 AfterInstall:
    - location: InstallScript.sh
      timeout: 600
