version: 0.2

phases: 
  install: 
    commands: 
      - apt update
      - apt upgrade
      - apt install -y software-properties-common
      - apt-add-repository --yes --update ppa:ansible/ansible
      - apt install -y ansible
      - ansible-galaxy collection install community.mysql
      - ansible-galaxy collection install community.aws
      - apt-get install -y composer
  build: 
    commands: 
      - ls -al
      - export COMPOSER_HOME="$HOME/.config/composer"
      - apt install -y python3-pip
      - python3 -m pip install boto3
      - ansible-playbook RDS.yml
      - composer install
