version: 0.2

phases: 
  install: 
    commands: 
      - apt-add-repository --yes --update ppa:ansible/ansible
      - apt install -y ansible
      - apt-get install -y composer
      - pip install botocore
  build: 
    commands: 
      - export COMPOSER_HOME="$HOME/.config/composer"
      - ansible-galaxy collection install community.mysql
      - ansible-galaxy collection install community.aws
      - ansible-playbook RDS.yml
      - composer install
