version: 0.2

phases: 
  install: 
    commands: 
      - sudo apt update
      - sudo apt upgrade -y
      - sudo apt install -y software-properties-common
      - sudo apt-add-repository --yes --update ppa:ansible/ansible
      - sudo apt install -y ansible
      - sudo apt-get install -y composer
  build: 
    commands: 
      - sudo export COMPOSER_HOME="$HOME/.config/composer"
      - sudo apt install -y python3-pip
      - sudo python3 -m pip install boto3
      - sudo python3 -m pip install botocore
      - sudo pip3 freeze
      - sudo ansible-galaxy collection install community.mysql
      - sudo ansible-galaxy collection install community.aws
      - sudo ansible-playbook RDS.yml -e 'ansible_python_interpreter=/usr/bin/python3'
      - sudo composer install
