version: 0.2

phases: 
  install: 
    commands: 
      - apt update
      - apt upgrade -y
      - apt install -y software-properties-common
      - apt-add-repository --yes --update ppa:ansible/ansible
      - apt install -y ansible
      - ansible-galaxy collection install community.mysql
      - ansible-galaxy collection install community.aws
      - apt-get install -y composer
  build: 
    commands: 
      - ls -al
      - export COMPOSER_HOME="$HOME/.config/composer"
      - apt install -y python3-pip
      - python3 -m pip install --force-reinstall boto3
      - python3 -m pip install --force-reinstall botocore
      - pip3 freeze
      - ansible --version
      - ansible-playbook RDS.yml -e 'ansible_python_interpreter=/usr/bin/python3'
      - composer install
